// Fresh manifest - auto-generated, but include stub for build compatibility
// This file is normally auto-generated by Fresh CLI

export const manifest = {
  routes: [],
  islands: [],
  baseUrl: import.meta.url,
};

export default manifest;
